In [1]:
import tensorcircuit as tc

In [2]:
circ = tc.QuditCircuit(2, 3)

In [3]:
circ.h(0)
circ.x(1)
circ.csum(0, 1)

In [4]:
circ.sample(1025, format='count_dict_bin')

{'01': 347, '12': 331, '20': 347}

In [5]:
circ.state()

array([0.        +0.j, 0.57735026+0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.57735026+0.j, 0.57735026+0.j, 0.        +0.j,
       0.        +0.j], dtype=complex64)

In [6]:
circ.measure(0, 1, with_prob=True)

(array([0., 0.], dtype=float32), np.float32(1.0))

In [5]:
c = tc.Circuit(2)

In [6]:
c.h(0, 1)
c.cnot(0, 1)

IndexError: list index out of range

In [10]:
c.amplitude('11')

array(0.70710677+0.j, dtype=complex64)

In [11]:
c.wavefunction()

[Node
(
name : 'qb-0',
tensor : 
array([1.+0.j, 0.+0.j], dtype=complex64),
edges : 
[
Edge('h'[1] -> 'qb-0'[0] )
] 
), Node
(
name : 'qb-1',
tensor : 
array([1.+0.j, 0.+0.j], dtype=complex64),
edges : 
[
Edge('cnot'[3] -> 'qb-1'[0] )
] 
), Gate(
    name: 'h',
    tensor:
        array([[ 0.70710677+0.j,  0.70710677+0.j],
               [ 0.70710677+0.j, -0.70710677+0.j]], dtype=complex64),
    edges: [
        Edge('cnot'[2] -> 'h'[0] ),
        Edge('h'[1] -> 'qb-0'[0] )
    ]), Gate(
    name: 'cnot',
    tensor:
        array([[[[1.+0.j, 0.+0.j],
                 [0.+0.j, 0.+0.j]],
        
                [[0.+0.j, 1.+0.j],
                 [0.+0.j, 0.+0.j]]],
        
        
               [[[0.+0.j, 0.+0.j],
                 [0.+0.j, 1.+0.j]],
        
                [[0.+0.j, 0.+0.j],
                 [1.+0.j, 0.+0.j]]]], dtype=complex64),
    edges: [
        Edge(Dangling Edge)[0],
        Edge(Dangling Edge)[1],
        Edge('cnot'[2] -> 'h'[0] ),
        Edge('cnot'[3] -

array([0.70710677+0.j, 0.        +0.j, 0.        +0.j, 0.70710677+0.j],
      dtype=complex64)